FROM rust:alpine

WORKDIR /app/www
COPY . .
RUN apk add --no-cache openssl-dev musl-dev
RUN cargo build --release

EXPOSE 3003
ENV RUST_LOG=info
ENV BASE_PATH=file-upload
CMD ["cargo", "run", "--release"]