FROM rust:alpine as builder

WORKDIR /app/www
COPY . .
RUN apk add --no-cache openssl-dev musl-dev
ENV BASE_PATH=file-upload
RUN cargo install --path .

FROM alpine:latest

ENV RUST_LOG=info
EXPOSE 3003
COPY --from=builder /usr/local/cargo/bin/file-upload /usr/local/bin/file-upload
CMD ["file-upload"]